# Generated by Django 3.2.6 on 2021-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
