# Generated by Django 3.2.6 on 2021-08-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloB', '0002_empleado_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ModeloB.tipo'),
            preserve_default=False,
        ),
    ]
