# Generated by Django 3.2.6 on 2021-08-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloB', '0003_auto_20210823_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='categ',
            field=models.ManyToManyField(to='ModeloB.categoria'),
        ),
    ]
