# Generated by Django 3.2.6 on 2021-08-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloB', '0005_auto_20210823_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
        migrations.AddField(
            model_name='client',
            name='dpi',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='DPI'),
            preserve_default=False,
        ),
    ]
