# Generated by Django 3.2.6 on 2021-10-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloB', '0006_auto_20210826_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
