# Generated by Django 3.2.6 on 2021-10-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloB', '0009_auto_20211018_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
