# Generated by Django 3.2.6 on 2021-10-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloB', '0010_auto_20211024_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dpi',
            field=models.CharField(max_length=10, unique=True, verbose_name='NIT'),
        ),
    ]
