# Generated by Django 3.2.6 on 2021-10-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloB', '0011_alter_client_dpi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dpi',
            new_name='nit',
        ),
    ]
